app/urls.py
from django.urls import path
from .views import blog, user

app_name = 'app1'
urlpatterns = [
    # ex: /blog  主页
    path('', blog.Index.as_view(), name='index'),
    # ex: /blog/detail/1  博客详情
    path('detail/<int:blog_id>/', blog.Article.as_view(), name='article'),
    # ex: /blog/category/python  分类列表
    path('category/<str:category_id>/', blog.Article_category.as_view(), name='category'),
    # ex: /blog/tag/mysql   标签文章列表
    path('tag/<str:tag_id>/', blog.Article_tag.as_view(), name='tag'),
    # ex: /blog/search?=xxx   搜索
    path('search/', blog.Search.as_view(), name='search'),
    # 用户登陆
    path('sign_in/', user.SignIn.as_view(), name='sign_in'),
    # 用户注册
    path('sign_up/', user.SignUp.as_view(), name='sign_up'),
    # 用户注销
    path('sign_out/', user.SignOut.as_view(), name='sign_out'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/', xadmin.site.urls),
    path('blog/', include('app.urls')),
    path('comments/', include('django_comments.urls')),
]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    """用户信息"""

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class Category(models.Model):
    """博客分类"""
    name = models.CharField(verbose_name='博客分类', max_length=15)
    create_time = models.DateField(verbose_name='创建时间', auto_now_add=True)
    change_time = models.DateField(verbose_name='修改时间', auto_now=True)

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(verbose_name='标签', max_length=15)
    create_time = models.DateField(verbose_name='创建时间', auto_now_add=True)
    change_time = models.DateField(verbose_name='修改时间', auto_now=True)

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=30, verbose_name='博客标题')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    content = models.TextField(verbose_name='内容')
    create_time = models.DateField(auto_now_add=True, verbose_name='创建时间')
    change_time = models.DateField(auto_now=True, verbose_name='修改时间')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='文章分类')
    tags = models.ManyToManyField(Tag)
    view_num = models.IntegerField(default=0, verbose_name='阅读')
    like_num = models.IntegerField(default=0, verbose_name='点赞')

    class Meta:
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

app/views/blog.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models.aggregates import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from ..models import *


# Create your views here.


def paginator(article, page_num):
    """分页相关数据函数"""
    paginator_num = Paginator(article, 5)  # 每页数目
    page_range = paginator_num.page_range  # 分页迭代
    page_next = paginator_num.num_pages  # 分页总数
    page_list = paginator_num.page(page_num)  # 每页数据
    paginator_data = {
        'page_list': page_list,
        'page_range': page_range,
        'page_next': page_next
    }
    return paginator_data


def hot():
    """热门文章/标签云/分类数据"""
    category_list = Category.objects.all()
    hot_list = Blog.objects.all().order_by('-view_num')[:5]
    tag_list = Tag.objects.annotate(blog_num=Count('blog'))

    public_data = {
        'category_list': category_list,
        'hot_list': hot_list,
        'tag_list': tag_list
    }
    return public_data


class Index(View):
    """首页页面"""

    def get(self, request):
        blog_list = Blog.objects.all().order_by('-create_time')
        page_num = int(request.GET.get('page_num', '1'))
        paginator_data = paginator(blog_list, page_num)

        # 热门文章数据
        public_data = hot()

        data = {
            'blog_list': blog_list,
            'paginator_data': paginator_data,
            'public_data': public_data
        }
        return render(request, 'index.html', context=data)


class Article(View):
    """博客详情页面"""

    def get(self, request, blog_id):
        article = Blog.objects.get(pk=blog_id)

        # 点赞数
        if request.GET.get('like'):
            like_status = request.GET.get('like')
        else:
            like_status = 0
        article.like_num += int(like_status)
        article.save()

        # 阅读数
        article.view_num += 1
        article.save()

        # 热门文章数据
        public_data = hot()

        data = {
            'article_data': article,
            'public_data': public_data
        }
        return render(request, 'article.html', context=data)


class Article_category(View):
    """分类"""

    def get(self, request, category_id):
        blog_list = Blog.objects.filter(category__name=category_id).order_by('-create_time')
        articles_total = blog_list.count()
        page_num = int(request.GET.get('page_num', '1'))
        paginator_data = paginator(blog_list, page_num)

        # 热门文章数据
        public_data = hot()

        data = {
            'article_data': blog_list,
            'paginator_data': paginator_data,
            'articles_total': articles_total,
            'public_data': public_data
        }

        return render(request, 'category.html', context=data)


class Article_tag(View):
    """根据tag标签分类的文章"""

    def get(self, request, tag_id):
        blog_list = Blog.objects.filter(tags__name=tag_id)
        page_num = int(request.GET.get('page_num', '1'))
        paginator_data = paginator(blog_list, page_num)
        tag_id = tag_id
        public_data = hot()

        data = {
            'article_data': blog_list,
            'paginator_data': paginator_data,
            'public_data': public_data,
            'tag_id': tag_id
        }

        return render(request, 'tag.html', context=data)


class Search(View):
    """搜索"""

    def get(self, request):
        search_text = request.GET.get('key')
        blog_list = Blog.objects.filter(Q(title__icontains=search_text) | Q(content__icontains=search_text)).order_by(
            '-create_time')
        articles_total = blog_list.count()
        page_num = int(request.GET.get('page_num', '1'))
        paginator_data = paginator(blog_list, page_num)

        # 热门文章数据
        public_data = hot()

        data = {
            'paginator_data': paginator_data,
            'search_text': search_text,
            'articles_total': articles_total,
            'public_data': public_data
        }

        return render(request, 'search.html', context=data)

app/views/user.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views.generic.base import View
from ..models import *


class SignIn(View):
    """登陆页面"""

    def get(self, request):
        return render(request, 'sign_in.html', context=None)

    def post(self, request):
        _user = request.POST['user']
        _pwd = request.POST['pwd']
        user = authenticate(username=_user, password=_pwd)
        if user is not None:
            login(request, user)
            return redirect('/blog/')
        else:
            return redirect('/blog/sign_up/')


class SignUp(View):
    """注册页面"""

    def get(self, request):
        return render(request, 'sign_up.html', context=None)

    def post(self, request):
        user = request.POST['user']
        pwd = request.POST['pwd']
        # create_user方法自动save
        user_sign_up = User.objects.create_user(username=user, email=None, password=pwd)

        return redirect('/blog/sign_in/')


class SignOut(View):
    """登出页面"""

    def get(self, request):
        logout()
        return redirect('/blog/sign_in/')

app/templates/article.html
{% extends 'base.html' %}

{% block title %}
<title>{{ article_data.title }}</title>
{% endblock %}

{% block index %}
<p>{{ article_data.content }}</p>

<form action="{% url 'app1:article' article_data.id %}" method="get">
    <button type="submit" name="like" value="1" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> 点赞{{ article_data.like_num }}
    </button>
</form>


{% block comment %}
{% load comments %}
{% get_comment_form for article_data as form %}
<form action="{% comment_form_target %}" method="post">{% csrf_token %}
    {# 必须的字段 #}
    {{ form.object_pk }}
    {{ form.content_type }}
    {{ form.timestamp }}
    {{ form.site }}
    {{ form.submit_date }}
    {{ form.security_hash }}
    <p><label for="id_name">名字: </label>{{ form.name }}</p>
    <p><label for="id_email">邮箱: </label>{{ form.email }}</p>
    <p><label for="id_url">站点: </label>{{ form.url }}</p>
    <p><label for="id_comment">内容: </label>{{ form.comment }}</p>
    <span style="display: none;">{{ form.honeypot }}</span>

    <input type="submit" value="提交"/>
</form>
{% get_comment_count for article_data as comment_count %}
<p>评论数：{{ comment_count }}:</p>

{% get_comment_list for article_data as comment_list %}
{% for comment in comment_list %}
<p>评论人: {{ comment.user_name }} 发表于 {{ comment.submit_date }}</p>
<p>内容：{{ comment.comment }}</p>
{% endfor %}
{% endblock %}

{% endblock %}

{% block pagination %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>xxxx</title>
    {% endblock %}

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!--load all styles -->

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'app1:index' %}">首页</a>
        </div>
        <!--搜索开始-->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% for category in public_data.category_list %}
                <li><a href="{% url 'app1:category' category.name %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
            <form class="navbar-form navbar-left" action="{% url 'app1:search' %}" method="get">
                <div class="form-group">
                    <input type="text" class="form-control" name="key" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>

            <!--登陆开始-->
            <form class="navbar-form navbar-left" action="{% url 'app1:sign_in' %}" method="get">
                <div class="form-group">
                    <button type="submit" class="btn btn-default">登陆</button>
                </div>
            </form>

            <!--注册开始-->
            <form class="navbar-form navbar-left" action="{% url 'app1:sign_up' %}" method="get">
                <div class="form-group">
                    <button type="submit" class="btn btn-default">注册</button>
                </div>
            </form>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="row">
    <div class="col-md-8">
        {% block index %}
        {% endblock %}

        <!--分页开始-->
        {% block pagination %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="?page_num=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% for page in paginator_data.page_range %}
                <li><a href="?page_num={{ page }}">{{ page }}</a></li>
                {% endfor %}
                <li>
                    <a href="?page_num={{ paginator_data.page_next }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!--分页结束-->
        {% endblock %}
    </div>

    <div class="col-md-4">

        <h5>热门文章</h5>
        {% for hot_blog in public_data.hot_list %}
        <ul class="list-group">
            <li class="list-group-item"><a href="{% url 'app1:article' hot_blog.id %}">{{ hot_blog.title }}<span
                    class="badge">阅读：{{ hot_blog.view_num }}  点赞：{{hot_blog.like_num}}</span></a></li>
        </ul>
        {% endfor %}

        <h5>标签云</h5>
        {% for tag_name in public_data.tag_list %}
        <a href="{% url 'app1:tag' tag_name.name %}">{{ tag_name.name }} <span
                class="badge">{{ tag_name.blog_num }}</span></a>
        {% endfor %}

        <h5>最新评论</h5>

    </div>
</div>
</body>
</html>

app/templates/category.html
{% extends 'base.html' %}

{% block title %}
{% for article in article_data %}
<title>{{ article.category }}分类文章</title>
{% endfor %}
{% endblock %}

{% block index %}
<h4>共有{{ articles_total }} 篇博客！</h4>
{% for blog in paginator_data.page_list %}
<ul class="list-group">
    <li class="list-group-item"><a href="{% url 'app1:article' blog.id %}">{{ blog.title }}<span class="badge">阅读：{{ blog.view_num }}  点赞：{{blog.like_num}}</span></a></li>
</ul>
{% endfor %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
<title>我的博客</title>
{% endblock %}

<!--正文开始-->
{% block index %}
{% for blog in paginator_data.page_list %}
<ul class="list-group">
    <li class="list-group-item"><a href="{% url 'app1:article' blog.id %}">{{ blog.title }}<span class="badge">阅读：{{ blog.view_num }}  点赞：{{blog.like_num}}</span></a></li>
</ul>
{% endfor %}

<!--正文结束-->
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block title %}
<title>搜索： {{ search_text }}</title>
{% endblock %}

{% block index %}
<h4>共搜索有{{ articles_total }} 篇博客！</h4>
<!--搜索文章列表-->
{% for blog in paginator_data.page_list %}
<ul class="list-group">
    <li class="list-group-item"><a href="{% url 'app1:article' blog.id %}">{{ blog.title }}<span class="badge">阅读：{{ blog.view_num }}  点赞：{{blog.like_num}}</span></a></li>
</ul>
{% endfor %}

{% endblock %}

<!--分页开始-->
{% block pagination %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
      <a href="?key={{search_text}}&page_num=1" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for page in paginator_data.page_range %}
    <li><a href="?key={{search_text}}&page_num={{ page }}">{{ page }}</a></li>
    {% endfor %}
    <li>
      <a href="?key={{search_text}}&page_num={{ paginator_data.page_next }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

app/templates/sign_in.html
{% extends 'base.html' %}

{% block title %}
<title>登录</title>
{% endblock %}

<!--正文开始-->
{% block index %}
<form action="{% url 'app1:sign_in' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">用户名</label>
        <input type="text" name="user" class="form-control" id="exampleInputEmail1" placeholder="name">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
        <input type="password" name="pwd" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-default">登录</button>
</form>

<!--正文结束-->
{% endblock %}

{% block pagination %}
{% endblock %}

app/templates/sign_up.html
{% extends 'base.html' %}

{% block title %}
<title>注册</title>
{% endblock %}

<!--正文开始-->
{% block index %}
<form action="{% url 'app1:sign_up' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">用户名</label>
        <input type="text" name="user" class="form-control" id="exampleInputEmail1" placeholder="name">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
        <input type="password" name="pwd" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-default">注册</button>
</form>

<!--正文结束-->
{% endblock %}

{% block pagination %}
{% endblock %}

app/templates/tag.html
{% extends 'base.html' %}

{% block title %}
<title>{{ tag_id }}</title>
{% endblock %}

{% block index %}
{% for blog in paginator_data.page_list %}
<ul class="list-group">
    <li class="list-group-item"><a href="{% url 'app1:article' blog.id %}">{{ blog.title }}<span class="badge">阅读：{{ blog.view_num }}  点赞：{{blog.like_num}}</span></a></li>
</ul>
{% endfor %}
{% endblock %}